### ISSUE TITLE
Launch to heroku

### ISSUE THREAD

**Issue by MrMaksimize** [opensandiego/open-dsd-notifications#3]

**Comment by bcipolli** [comment]
This has been launched to heroku, but the feed format isn't working. The "id" field is not propagating:
https://github.com/citygram/citygram-services/issues/33#issuecomment-142006258

Not sure if this line is failing because the capitalization of `CaseId` is wrong, or if the heroku app needs to be re-launched with the latest code.
https://github.com/opensandiego/open-dsd-notifications/blob/master/app.js#L39

@MrMaksimize can you take a look?

**Comment by bigfleet** [comment]
I'll chime in on a nicety here, too-- the title gets sent via SMS, so I usually prefer it not having HTML markup in it as well.

**Comment by bcipolli** [comment]
This is fixed and can be closed.
