### ISSUE TITLE
Permit / Code Violation Descriptions

### ISSUE THREAD

**Issue by MrMaksimize** [opensandiego/open-dsd-notifications#5]
Please see below for some of the data coming in from the OpenDSD endpoint.  

The problem is -- we don't fully understand what a lot of these things mean.  Namely:
- CaseId
- CaseDepiction
- SortableStreetAddress
- APN
- Mapreference

In addition, I don't fully understand what is the difference between the various  code violations / approvals/ ministerials approvals and other object types on OpenDSD.  

IMO this should be documented.

We need to provide a description in a file in the repo

I created a file here:
[dsd-description](https://github.com/opensandiego/open-dsd-notifications/blob/master/dsdDescriptions.md)
And here's how you can edit it (you have to be logged in and have access to the repo).
![edit](http://take.ms/N9EnQ)

```
{  
         "SouthWestLatitude":null,
         "SouthWestLongitude":null,
         "NorthEastLatitude":null,
         "NorthEastLongitude":null,
         "SearchType":null,
         "RowNum":null,
         "CaseId":90417,
         "CaseDepiction":"1",
         "Description":"STRUCTURAL/RES - TRANS TO I4G 3/21/07 [Addr: 3051 IVY ST APN: 539-161-08 Owner: GRAY, ROBERT M] ",
         "OpenDate":"2002-04-25T00:00:00",
         "CloseDate":null,
         "StreetAddress":"3051 IVY ST ",
         "SortableStreetAddress":"IVY ST 0000003051 ",
         "APN":"539-161-08-00",
         "MapReference":"1289-E1",
         "Longitude":-117.128457,
         "Latitude":32.72832
      },

```

**Comment by ahempton** [comment]
These appear to be fields from the Code Enforcement application.

•CaseId -- this would be the Code Enforcement Case ID number
 •CaseDepiction -- I'm not sure what this stands for.  I'm checking with Jim Myers to see if there is a document that describes all of the field labels.
 •SortableStreetAddress  -- it looks like this puts the Street Name first, and the street number after so that it can be sorted in a list
 •APN  -- this is the Assessors Parcel Number
 •Mapreference -- I believe this is the Thomas Bros. Map Code

**Comment by ahempton** [comment]
Here's more info on the Code Enforcement XML dataset:  http://www.sandiego.gov/development-services/opendsd/codenforcement.shtml

**Comment by ahempton** [comment]
I should probably provide a brief overview of the info in Open DSD - this is oversimplified, but may help to describe things.

There are essentially three parts of the system:
1.  Code Enforcement
2.  Ministerial Permits
3.  Discretionary Permits

Code Enforcement is primarily complaint driven and consists of complaints, which are entered in the system as Cases and assigned a Case Number and an Investigator.  The investigator takes a series of steps, such as sending out an initial notice, investigating the site/research, etc.  Various timelines and reminder/follow-up dates are provided for follow-up and action toward correcting the complaint before the case is eventually closed.

Ministerial permits (Process 1) are generally construction permits which are obtained via a Staff-level/other-the-counter type decision.  These can include things like building permits, right-of-way permits, etc.

Discretionary permits consist of projects where a Process 2 or higher decision is required before a construction permit/ministerial permit can be issued.  

Process 1 - staff decision 
Process 2 - staff decision, may be appealed to Planning Commission for a final decision
Process 3 - Hearing Officer hearing, may be appealed to Planning Commission
Process 4 - Planning Commission decision, may be appealed to City Council
Process 5 - City Council decision (receives a Planning Commission recommendation first)

I can provide more information about specific areas/questions

**Comment by jerryhall** [comment]
Would it help if we summarized everything in a single doc to help describe... like this:

#OpenDSD Website
##Development Services Department
###City of San Diego

[OpenDSD Website](http://www.sandiego.gov/development-services/opendsd/index.shtml)
[Search by Data Tips](http://www.sandiego.gov/development-services/opendsd/pdf/datatips.pdf) 

There are essentially three parts of the system:

###Code Enforcement
Code Enforcement Cases [map search](http://opendsd.sandiego.gov/web/maps/cecase)
Code Enforcement is primarily complaint driven and consists of complaints, which are entered in the system as Cases and assigned a Case Number and an Investigator. The investigator takes a series of steps, such as sending out an initial notice, investigating the site/research, etc. Various timelines and reminder/follow-up dates are provided for follow-up and action toward correcting the complaint before the case is eventually closed.

Dataset [Information](http://www.sandiego.gov/development-services/opendsd/codenforcement.shtml)
**Dataset Legend**
_CaseId_ -- this would be the Code Enforcement Case ID number
_CaseDepiction_ -- I'm not sure what this stands for. I'm checking with Jim Myers to see if there is a document that describes all of the field labels.
_SortableStreetAddress_ -- it looks like this puts the Street Name first, and the street number after so that it can be sorted in a list
_APN_ -- this is the Assessors Parcel Number
_Mapreference_ -- I believe this is the Thomas Bros. Map Code

###Ministerial Permits
Ministerial Permit Approvals [map search](http://opendsd.sandiego.gov/web/maps/approvalsministerial)
Ministerial permits (Process 1) are generally construction permits which are obtained via a Staff-level/other-the-counter type decision. These can include things like building permits, right-of-way permits, etc.

###Discretionary Permits
Discretionary Permit Approvals [map search](http://opendsd.sandiego.gov/web/maps/approvalsdiscretionary)
Discretionary permits consist of projects where a Process 2 or higher decision is required before a construction permit/ministerial permit can be issued.

Development Processes Summary
**Process 1** - staff decision 
**Process 2** - staff decision, may be appealed to Planning Commission for a final decision
**Process 3** - Hearing Officer hearing, may be appealed to Planning Commission
**Process 4** - Planning Commission decision, may be appealed to City Council
**Process 5** - City Council decision (receives a Planning Commission recommendation first)

**Comment by bcipolli** [comment]
This should be written into an MD file within the repo. @ahempton or @jerryHall is this something you'd be willing to do?

**Comment by bcipolli** [comment]
Temporarily assigning to myself, while we find someone who can push this forward.

**Comment by ahempton** [comment]
What is an MD file?  Metadata?

**Comment by bcipolli** [comment]
Markdown. Same as RST (restructured text). @jerryHall 's post above uses the necessary syntax, as does the README.md from this repo. I think @MrMaksimize has some instructions above as well.

**Comment by ahempton** [comment]
Got it - thanks

I'm trying to get more familiar with GitHub... Trying to respond to requests of me but I feel like I might be missing some of them

**Comment by bcipolli** [comment]
OK, I followed @MrMaksimize 's instructions and added info this to the file:
https://github.com/opensandiego/open-dsd-notifications/blob/master/dsdDescriptions.md

I also linked the file from README.md. So, we're done here :)
